Add missing whitespace (#1318)
Add missing whitespace

SUMMARY

Add missing whitespace
ERROR: Found 2 pep8 issue(s) which need to be resolved:
--
1058 | 2023-01-04 10:00:26.447222 \| controller \| ERROR: plugins/module_utils/elbv2.py:48:8: E275: missing whitespace after keyword
1059 | 2023-01-04 10:00:26.447227 \| controller \| ERROR: plugins/module_utils/waf.py:140:20: E275: missing whitespace after keyword



ISSUE TYPE


Bugfix Pull Request

COMPONENT NAME

plugins/module_utils/elbv2.py
plugins/module_utils/waf.py

Reviewed-by: Mark Chappell <None>
Reviewed-by: Alina Buzachis <None>