Add 'alternative' for EC2_REGION deprecation for non-module plugins (#2185)
SUMMARY
Adds "alternative" key to documentation for deprecated EC2_REGION env variable.
ISSUE TYPE

Docs Pull Request

COMPONENT NAME
plugins/doc_fragments/region.py
ADDITIONAL INFORMATION
Fixes sanity issue:
 ERROR: Found 5 validate-modules issue(s) which need to be resolved:
ERROR: plugins/inventory/aws_ec2.py:0:0: invalid-documentation: DOCUMENTATION.options.region.env.1.deprecated.Any('alternatives', 'alternative', msg=None): required key not provided @ data['options']['region']['env'][1]['deprecated'][Any('alternatives', 'alternative', msg=None)]. Got None
ERROR: plugins/inventory/aws_rds.py:0:0: invalid-documentation: DOCUMENTATION.options.region.env.1.deprecated.Any('alternatives', 'alternative', msg=None): required key not provided @ data['options']['region']['env'][1]['deprecated'][Any('alternatives', 'alternative', msg=None)]. Got None
ERROR: plugins/lookup/aws_account_attribute.py:0:0: invalid-documentation: DOCUMENTATION.options.region.env.1.deprecated.Any('alternatives', 'alternative', msg=None): required key not provided @ data['options']['region']['env'][1]['deprecated'][Any('alternatives', 'alternative', msg=None)]. Got None
ERROR: plugins/lookup/secretsmanager_secret.py:0:0: invalid-documentation: DOCUMENTATION.options.region.env.1.deprecated.Any('alternatives', 'alternative', msg=None): required key not provided @ data['options']['region']['env'][1]['deprecated'][Any('alternatives', 'alternative', msg=None)]. Got None
ERROR: plugins/lookup/ssm_parameter.py:0:0: invalid-documentation: DOCUMENTATION.options.region.env.1.deprecated.Any('alternatives', 'alternative', msg=None): required key not provided @ data['options']['region']['env'][1]['deprecated'][Any('alternatives', 'alternative', msg=None)]. Got None

Reviewed-by: Alina Buzachis
(cherry picked from commit 3c6ba70e6e3a7477a0fd2b96b754958e848cb76c)