Fix sanity errors happening with the ansible devel branch (#2146)
SUMMARY

Fix sanity errors happening with the ansible devel branch
ERROR: Found 5 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/ec2_vpc_vgw.py:504:13: used-before-assignment: Using variable 'deleted_vgw' before assignment
ERROR: plugins/modules/ecs_cluster.py:342:12: unreachable: Unreachable code
ERROR: plugins/modules/ecs_cluster.py:364:12: unreachable: Unreachable code
ERROR: plugins/modules/ecs_service.py:1251:12: unreachable: Unreachable code
ERROR: plugins/modules/ecs_service.py:1266:12: unreachable: Unreachable code

ISSUE TYPE

Bugfix Pull Request
Docs Pull Request
Feature Pull Request
New Module Pull Request

COMPONENT NAME

ADDITIONAL INFORMATION

Reviewed-by: Bikouo Aubin

This commit was initially merged in https://github.com/ansible-collections/community.aws
See: https://github.com/ansible-collections/community.aws/commit/008b515022ef0dbc19f964e174f803e48de9871f