fix(ci): lowerbound flake8 version to resolve pyflakes incompatibility (#3105)
SUMMARY
The linter check fails with some errors, as follows:
2026-09-23T11:59:52.9766077Z TypeError: FlakesChecker.parse_options() takes 2 positional arguments but 4 were given
...
2026-09-23T11:59:52.9777293Z AttributeError: type object 'FlakesChecker' has no attribute 'builtIns'

These issues stem from a pyflakes incompatibility, which you can see is getting installed in logs:
2026-09-23T11:59:52.2332181Z Downloading flake8-7.4.0-py2.py3-none-any.whl (57 kB)
2026-09-23T11:59:52.2814892Z Downloading pyflakes-4.0.0-py2.py3-none-any.whl (65 kB)

This can be observed in PR runs such as this one: https://github.com/ansible-collections/amazon.aws/actions/runs/35857640505/job/107169869539
The change in this PR bounds flake8 in the tox config to ensure that a compatible version of pyflakes gets installed according to flake8's requirements.
EDIT: Just noticed that flake8 v7.4.1 was released and addresses the incompatibility. Maybe the issue will go away on its own and we don't need this change. Maybe it's worth keeping though so I'll keep it open.
ISSUE TYPE

Bugfix Pull Request

Reviewed-by: Chyna Sanders
Reviewed-by: GomathiselviS <gosriniv@redhat.com>
Reviewed-by: Bikouo Aubin