ec2_vpc_dhcp_option - retry describe_dhcp_options on InvalidDhcpOptioID.NotFound (#1320)
ec2_vpc_dhcp_option - retry describe_dhcp_options on InvalidDhcpOptioID.NotFound

SUMMARY
Integration tests have been flakey because of
botocore.exceptions.ClientError: An error occurred (InvalidDhcpOptionID.NotFound) when calling the DescribeDhcpOptions operation: The dhcpOption ID 'dopt-005de86cff685951b' does not exist

While we're returned the ID, creation and propagation isn't always instant.  Allow for retries after creation of an optionset.
ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
ec2_vpc_dhcp_options
ADDITIONAL INFORMATION
Examples:
https://99b800ba2f338f8fe26c-b9e663698c5137b7c40d5b983da05750.ssl.cf5.rackcdn.com/1310/8b18a5ca6e49e02b0004c86cc3467e10b0757555/gate/integration-amazon.aws-16/23f54a3/job-output.txt
https://530531024c51fb0860cd-d325a0cf1bd8249f2d5115b3e7ba100c.ssl.cf5.rackcdn.com/1310/8b18a5ca6e49e02b0004c86cc3467e10b0757555/gate/integration-amazon.aws-16/3594443/job-output.txt
(note the failing ec2_vpc_net test is actually the DHCP option creation failing.  First time we get the exception, second time the option already exists so isn't "changed")

Reviewed-by: Alina Buzachis <None>