Address ansible-test sanity errors with whitespace and unused imports (#3100)
SUMMARY
These changes address the following issues uncovered with ansible-test sanity while adding the partner certification checker workflow:
  ERROR: Found 29 pep8 issue(s) which need to be resolved:
  ERROR: plugins/modules/rds_instance_param_group_info.py:80:1: E302: expected 2 blank lines, found 1
  ERROR: plugins/modules/rds_instance_param_group_info.py:83:1: W293: blank line contains whitespace
  ERROR: plugins/modules/rds_instance_param_group_info.py:90:1: W293: blank line contains whitespace
  ERROR: plugins/modules/rds_instance_param_group_info.py:96:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:958:1: E302: expected 2 blank lines, found 1
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:970:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:972:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:976:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:984:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:986:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:993:1: E302: expected 2 blank lines, found 1
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1000:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1007:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1015:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1023:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1031:1: E302: expected 2 blank lines, found 1
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1036:69: W291: trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1039:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1041:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1047:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1052:69: W291: trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1055:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1057:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1060:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1069:1: E302: expected 2 blank lines, found 1
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1074:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1076:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1081:1: W293: blank line contains whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1089:1: W293: blank line contains whitespace

  ERROR: Found 25 pylint issue(s) which need to be resolved:
  ERROR: plugins/module_utils/_rds/api.py:19:0: unused-import: Unused camel_dict_to_snake_dict imported from ansible.module_utils.common.dict_transformations
  ERROR: plugins/module_utils/_rds/api.py:22:0: unused-import: Unused is_boto3_error_code imported from botocore
  ERROR: plugins/modules/rds_instance_param_group_info.py:90:0: trailing-whitespace: Trailing whitespace
  ERROR: plugins/modules/rds_instance_param_group_info.py:96:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:970:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:972:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:976:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:984:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:986:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1000:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1007:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1015:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1023:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1036:68: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1039:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1041:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1047:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1052:68: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1055:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1057:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1060:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1074:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1076:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1081:0: trailing-whitespace: Trailing whitespace
  ERROR: tests/unit/plugins/module_utils/rds/test_rds_api.py:1089:0: trailing-whitespace: Trailing whitespace

First run of the workflow in my fork without these changes (job fails): https://github.com/oraNod/amazon.aws/actions/runs/35361899181/job/105654980777
Second run of the workflow with these changes (no failures): https://github.com/oraNod/amazon.aws/actions/runs/35609295814
ISSUE TYPE

Bugfix Pull Request

Reviewed-by: Bikouo Aubin
Reviewed-by: Mark Chappell